# Configuration preset for the official Persistence SS14 server.
# This file was written with the expectation that persistBase would be loaded first.
# Related docs https://docs.spacestation14.com/en/general-development/tips/config-file-reference.html

[game]
hostname = "[EN][HRP] Persistence SS14 | Fully persistent game world and characters"
desc = "Enjoy Space Station 14 where characters and the game world is 100% persistent. Create ships and entire space stations from scratch in an evolving player-driven economy. Write your characters own destiny in the ultimate collaborative storytelling experience of the season."
soft_max_players = 100
autosaveenabled = true
autosaveinterval = 60
panic_bunker.show_reason = true
panic_bunker.custom_reason = "The server is shutting down soon and is no longer accepting new connections."

[hub]
tags = "lang:en,region:am_n_w,rp:high"

[server]
rules_file = "PersistRuleset"

[ooc]
enable_during_round = false

[looc]
enabled_dead = true
enabled_crit = true

[ic]
flavor_text = true
punctuation = true

[atmos]
max_explosion_range = 4

[admin]
new_player_threshold = 600
alert.min_players_sharing_connection = 2
