# Base configuration preset for SS14 Persistence. On the official server this is loaded before persist.toml
# Related docs https://docs.spacestation14.com/en/general-development/tips/config-file-reference.html

[game]
hostname = "[NRP] Persistence Test Server"
desc = "Don't mind me, just using the base ConfigPreset!"
defaultpreset = "persist"
soft_max_players = 30
autosaveinterval = 60

[hub]
tags = "rp:none"

[infolinks]
bug_report = "https://github.com/michaelchessall/SS14-Persistence/issues/new/choose"
discord    = "https://discord.gg/PRjRkAN5NU"
github     = "https://github.com/michaelchessall/SS14-Persistence"

[server]
id = "Persistence"
